### ISSUE TITLE
/people endpoint: created/modified_date should be in ISO format

### ISSUE THREAD

**Issue by j-ro** [anuditverma/OSDI-Implementation#10]
This should be specified in the spec but it's not right now...

So something like:

```
2015-08-06T16:26:01Z
```

Rather than:

```
2/10/2015
```

**Comment by anuditverma** [comment]
I think this field is also not supported in the civi system so I just used the php date("Y/m/d") function as an example for the time being. I need to clarify this as well.

**Comment by joemcl** [comment]
Anudit, please use the API Explorer in Civi ( Help -> Developer -> API Explorer ) then
Entity: Contact, Action: getfields to see all the fields in Contact. Contacts can be people, organizations or households. There is actually a field called created_date. The format is like  2013-02-08 16:33:09 . Please see below. 

},
        "created_date": {
            "name": "created_date",
            "type": 256,
            "title": "Created Date",
            "description": "When was the contact was created.",
            "required": false,
            "export": true,
            "where": "civicrm_contact.created_date",
            "headerPattern": "",
            "dataPattern": "",
            "default": "NULL"

**Comment by joemcl** [comment]
Also see:

{
            "name": "modified_date",
            "type": 256,
            "title": "Modified Date",
            "description": "When was the contact (or closely related entity) was created or modified or deleted.",
            "required": false,
            "export": true,
            "where": "civicrm_contact.modified_date",
            "headerPattern": "",
            "dataPattern": "",
            "default": "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
        },

**Comment by joemcl** [comment]
I'll nail down the exact format for created_date and modified_date.  Although, Anudit, that should be discoverable from the API Explorer, not sure it is.

FYI, see an (possibly dated ) ERD here - http://wiki.civicrm.org/confluence/display/CRMDOC/CiviCRM+data+architecture 
I'll create or ask for help in creating an update using MySQL Workbench., the Civi wiki needs it.

And re custom fields, "[a] list of objects that can be extended with custom data can be found at: 

http://d45.demo.civicrm.org/civicrm/admin/custom/group?action=add&reset=1

log in with ID demo, password demo

Click on the 'Used for' drop down to see the full list."

**Comment by eileenmcnaughton** [comment]
Yep - as Joe says those fields are mysql timestamp fields  - you should read up on that here http://dev.mysql.com/doc/refman/5.6/en/timestamp-initialization.html because mysql interprets the timestamp fields into a timezone for you & that might not be what you want

**Comment by joemcl** [comment]
Re custom fields , see this link rather  - 

http://d45.demo.civicrm.org/civicrm/admin/custom/group?action=add&reset=1

log in with ID demo, password demo

**Comment by joemcl** [comment]
Eileen - if we want to switch to using UTC time for created_date and modified _date going forward - for OSDI API (and other APIs) purposes - but have that displayed to a user in Civi as local time as set in the user's preferences - will that be a big pain to do?

**Comment by eileenmcnaughton** [comment]
mysql converts it to the timezone of the mysql selection - so you need to set that correctly - or adjust for it in php afterwards

**Comment by anuditverma** [comment]
Fixed https://github.com/anuditverma/OSDI-Implementation/commit/4b2211451e6c45bc8ff0bba3a14cb4e7545bf28f -dates are in ISO format, though some of the records have modified_date fields empty so default date is shown there. This will be fixed altogether in issue https://github.com/anuditverma/OSDI-Implementation/issues/2
