### ISSUE TITLE
/people endpoint: email addresses is an array

### ISSUE THREAD

**Issue by j-ro** [anuditverma/OSDI-Implementation#11]
You have:

```
"email_addresses": {
    "primary": true,
    "address": "grants@airmail.org"
  }
```

It should be:

```
"email_addresses": [
          {
            "primary": true,
            "address": "abb@b.com"
          }
        ]
```

**Comment by anuditverma** [comment]
This has been fixed here https://github.com/anuditverma/OSDI-Implementation/commit/cd6bd5712ea3ff974a265838b3b0495898edaf53 & https://github.com/anuditverma/OSDI-Implementation/commit/952f8619479c878d0147ecdd5f6a944221d07fda
