### ISSUE TITLE
/people endpoint: ID field shouldn't exist, identifiers needs formatting

### ISSUE THREAD

**Issue by j-ro** [anuditverma/OSDI-Implementation#3]
An `id` field is being returned, which it shouldn't be per OSDI spec. If you want to return it, you should namespace it, like `civi_crm:id`, but I think it's unnecessary.

Rather, you should put that ID in the identifiers array. The array should be formatted like `system_prefix:[id]`

So, right now you have:

```
"identifiers": [
    "osdi-person-[0]"
  ]
```

That should be:

```
"identifiers": [
    "civi_crm:0"
  ]
```

Also, note that the identifier should be a unique ID for that person on the civi system, that never changes. Since it'll be used for a link to that person.

**Comment by anuditverma** [comment]
I have fixed this one here https://github.com/anuditverma/OSDI-Implementation/commit/7cb0b99c0a559022fee840ac57c7633d129bbe5b

In civi system contact_id field is used as an unique identifier for the contacts.

**Comment by j-ro** [comment]
I'd say you might want to take it out of brackets. Right now I see "civi_crm:[1]" where "civi_crm:1" would be more typical.

**Comment by anuditverma** [comment]
Ok, will do it.

**Comment by anuditverma** [comment]
Fixed.
