### ISSUE TITLE
/people endpoint: implement individual person resources

### ISSUE THREAD

**Issue by j-ro** [anuditverma/OSDI-Implementation#4]
So, links like this:

```
/sites/default/ext/osdi/api/v3/People/index.php?id=1
```

That brings back just that person's resource who's ID is 1.

**Comment by anuditverma** [comment]
I have fixed this one here https://github.com/anuditverma/OSDI-Implementation/commit/5bfc10b3f9226abf274eac06347fb85cfdfa3aa6
Though I have created a new file "person.php" https://github.com/anuditverma/OSDI-Implementation/commit/45ecc5423c81a3e19f2c9edda3dc2db618be206e for returning the particular person's record when id is passed in the url.

**Comment by j-ro** [comment]
this is awesome! great job
