### ISSUE TITLE
/people endpoint: don't replicate fields as custom fields

### ISSUE THREAD

**Issue by j-ro** [anuditverma/OSDI-Implementation#5]
Right now, I'm getting resources on the test endpoint like this:

```
{
        "given_name": "",
        "family_name": "",
        "email_addresses": {
          "primary": true,
          "address": "fixme.domainemail@example.org"
        },
        "identifiers": [
          "osdi-person-[0]"
        ],
        "id": "1",
        "created_date": "2015-07-03 14:19:10",
        "modified_date": "2015/08/08",
        "custom_fields": {
          "email": "fixme.domainemail@example.org",
          "full_name": " ",
          "event_code": "xx",
          "address": "",
          "zip": null,
          "pledge": "2"
        },
        "postal_addresses": [
          {
            "address_lines": [
              null
            ],
            "postal_code": null,
            "address_status": "Verified/Not Verified",
            "primary": "True/False"
          }
        ],
        "phone_numbers": [
          {
            "number": null
          }
        ],
        "_embedded": {
          "osdi:tags": []
        },
        "_links": {
          "self": {
            "href": "http://api.opensupporter.org/api/v1/people/X"
          },
          "addresses": {
            "href": "http://api.opensupporter.org/api/v1/people/X/addresses"
          },
          "question_answers": {
            "href": "http://api.opensupporter.org/api/v1/people/X/question_answers"
          },
          "osdi-tags": {
            "href": "http://api.opensupporter.org/api/v1/people/X/tags"
          }
        }
      }
```

So email has been made into a custom field, so has address, etc...

Custom fields should only contain custom field data, rather than duplications of data that already exists elsewhere in the resource.

**Comment by anuditverma** [comment]
Ok, so the custom fields should be left empty and should not be returned just like the issue here https://github.com/anuditverma/OSDI-Implementation/issues/2 ?

**Comment by j-ro** [comment]
If there are no custom fields (and I'm not sure if civi even supports custom fields, that would be a question for Eileen I think), then yeah, it wouldn't be returned at all.

If civi does support custom fields, then it would only be returned if that user has custom fields.

**Comment by joemcl** [comment]
Yes, CiviCRM has custom fields creation - they are custom to each installation - we have created a bunch for our Citizen Action of New York Civi install - and some CiviCRM extensions (modules) will create custom fields if installed.

**Comment by eileenmcnaughton** [comment]
CiviCRM definitely DOES support custom fields & the CiviCRM api will return them for Contacts if they are set up for them.
There is a CustomField api to get details about them

**Comment by anuditverma** [comment]
So If go to api explorer and getfields for the contact entity I am getting some fields in which "custom" is either prefixed or suffixed with them (but none like email, full name, event code etc) so I think I need to give those fields in my code anyway wiith "custom" attached to them and civi would return those fields if they were set up. Also I want to know If there is way to find out the custom fields associated with a particular contact via api explorer or any other way ?

**Comment by joemcl** [comment]
Just posted this on irc.civicrm.org looking for some help - "So I'm trying to do this using the API Explorer - Entity: Customfield Action: getlist only returns ID and label, for the first 10 records. I want to return all fields in all the Customfield records. No wiki documentation for getlist and unsure what is relevant code on GitHub"

**Comment by joemcl** [comment]
More on this, from my IRC post:
[14:09] <joemcl> found this, at 146 & 147in https://github.com/civicrm/civicrm-core/blob/23ba27836c75261ed04e1f4760310d33b3196615/api/v3/Generic/Getlist.php
[14:09] <joemcl> function _civicrm_api3_generic_getlist_params(&$request) { 147   $fieldsToReturn = array($request['id_field'], $request['label_field']);
[14:11] <joemcl> So can I modify this function using the API Explorer, or I think I'm doing a PR rather

**Comment by joemcl** [comment]
I did a PR, see https://github.com/civicrm/civicrm-core/pull/6452

**Comment by colemanw** [comment]
PR closed, as the problem was you were using the api incorrectly. I'm not exactly sure what you are trying to do but if it's:
- Fetch a list of custom fields defined for your site, you want "customField" "get"
- Fetch the actual data from custom fields for an entity, you want "customValue" "get"

**Comment by joemcl** [comment]
colemanw, thanks, now I "get" it.  :).

**Comment by colemanw** [comment]
Cool. I also updated the documentation on the wiki to avoid future confusion :)

**Comment by joemcl** [comment]
Coleman, thanks so much.

**Comment by joemcl** [comment]
Anudit, e-mail,address and zip aren't custom fields, they are core fields

**Comment by anuditverma** [comment]
This is one fixed, I have removed the fields from custom fields' array to prevent the duplication.. Fixes : https://github.com/anuditverma/org.civicrm.osdi/commit/135aed9f7ef28aff73ef43d11119aa4e4b3aee07 & https://github.com/anuditverma/org.civicrm.osdi/commit/cee48bdff6b62766d176a4e7aa6b4e5a96c9a04f

**Comment by anuditverma** [comment]
Removed custom fields. Fixes : https://github.com/anuditverma/org.civicrm.osdi/commit/20e9258bcdf1067715cf3e90aef17f30643339b4 & https://github.com/anuditverma/org.civicrm.osdi/commit/d4e1b6b931d706ab20c18afd4d55ff71804507c6

**Comment by j-ro** [comment]
yep, this seems good, as in there aren't custom field values where there shouldn't be. But I guess we want to show real custom fields in this hash at some point, right? Since Civi supports that.
