### ISSUE TITLE
/people endpoint: address isn't mapped correctly

### ISSUE THREAD

**Issue by j-ro** [anuditverma/OSDI-Implementation#6]
This user:

```
{
        "given_name": "Kiara",
        "family_name": "Roberts",
        "email_addresses": {
          "primary": true,
          "address": "kroberts40@testmail.com"
        },
        "identifiers": [
          "osdi-person-[1]"
        ],
        "id": "2",
        "created_date": "2015-07-03 14:19:10",
        "modified_date": "2015/08/08",
        "custom_fields": {
          "email": "kroberts40@testmail.com",
          "full_name": "Kiara Roberts",
          "event_code": "xx",
          "address": "287D Martin Luther King Ave NW",
          "zip": null,
          "pledge": "3"
        },
        "postal_addresses": [
          {
            "address_lines": [
              null
            ],
            "postal_code": null,
            "address_status": "Verified/Not Verified",
            "primary": "True/False"
          }
        ],
        "phone_numbers": [
          {
            "number": null
          }
        ],
        "_embedded": {
          "osdi:tags": []
        },
        "_links": {
          "self": {
            "href": "http://api.opensupporter.org/api/v1/people/X"
          },
          "addresses": {
            "href": "http://api.opensupporter.org/api/v1/people/X/addresses"
          },
          "question_answers": {
            "href": "http://api.opensupporter.org/api/v1/people/X/question_answers"
          },
          "osdi-tags": {
            "href": "http://api.opensupporter.org/api/v1/people/X/tags"
          }
        }
      }
```

This user has an address in custom fields, but that doesn't show up in address lines, but it should (and be removed from custom fields).

Address verified/unverified and true/false for primary should also not be there, or should have one value, not both if this is something civi supports.

**Comment by anuditverma** [comment]
I have fixed this issue, these are my commits https://github.com/anuditverma/OSDI-Implementation/commit/1718d4a5a3037f6bcdd6b62a6e01efe512eb4ec6 and https://github.com/anuditverma/OSDI-Implementation/commit/626c3648b470f105671360362a104a655b236242

So far what I have come across that Civi do no support address verification and similarly setting true/false values for emails etc. I need to confirm these first before finalizing this issue, I might have missed these support system.

**Comment by j-ro** [comment]
That's fine, if there's no verification, skip the field. Right now I'm seeing addresses like:

```
"address_lines": [
        [
          "766H Northpoint Blvd W",
          "",
          "",
          "NV, United States"
        ]
```

and 

```
[
          "",
          "",
          "",
          ", "
        ]
```

Blanks should not be shown. So if there's no address at all, the entire address object shouldn't be shown. If there are no lines, then the address_lines array shouldn't be shown. No blank lines like ""

But also, address lines refers only to the address portion, not the city, country, or state. As you can see above, you're outputting state and country in this array. Rather, they have their own fields in the address object: locality, region, country, postal_code.

So an address that's written like this:

```
1600 Pennsylvania Ave NW
#2
Washington, DC 20036
United States
```

Would be outputted in OSDI like:

```
"postal_addresses": [
    {
      "address_lines": [
        [
          "1600 Pennsylvania Ave NW",
          "#2"
        ]
      ],
      "locality": "Washington",
      "region": "DC",
      "postal_code": "20036",
      "country": "US",
      "primary": "true"
    }
  ]
```

**Comment by anuditverma** [comment]
I totally agree, blank fields should be skipped that's why I was trying to solve the issue https://github.com/anuditverma/OSDI-Implementation/issues/2
And I'll make the necessary changes in the address_lines to produce the output you suggested.

**Comment by j-ro** [comment]
sounds good!

**Comment by anuditverma** [comment]
Initiated a fix for this one https://github.com/anuditverma/org.civicrm.osdi/commit/b3dc8c77729584882614f0f4627795535a0db554

**Comment by j-ro** [comment]
I am seeing address correctly in address lines, but don't ever seem to see locality/region/postal_code/country, so the additional parts of an address may still need mapping.

**Comment by anuditverma** [comment]
Ok, I will add them too and Civi does have support for these fields.

**Comment by anuditverma** [comment]
Hey Jason, I have added those fields could you please a have look on the camus.
Here are the fixes : https://github.com/anuditverma/org.civicrm.osdi/commit/a57c46e03a7b02bd833abe2ec699ddf1f0740137 & https://github.com/anuditverma/org.civicrm.osdi/commit/be54a5d694daf690c54a485ed1e48266f6e9b73a

**Comment by j-ro** [comment]
Oh yeah, looking good! Only remaining issue here is that country needs to be in ISO 2 character format, so US instead of United States, for example.

**Comment by anuditverma** [comment]
Fixed now.
Fixes : https://github.com/anuditverma/org.civicrm.osdi/commit/a302e009fce7ad7af6944eff5ebe863d345799c0, https://github.com/anuditverma/org.civicrm.osdi/commit/f640b4345210aef39ae353ba80701d2206ef2640 & https://github.com/anuditverma/org.civicrm.osdi/commit/ece496ae627149314cf3ab24a1cd25ae607e9ad7
