### ISSUE TITLE
/people endpoint: links to tags, question answers, and addresses should be removed

### ISSUE THREAD

**Issue by j-ro** [anuditverma/OSDI-Implementation#8]
Since these are not valid links for /people -- addresses isn't valid at all, there is no OSDI address resource. And for tags, on people, there is a link to /taggings. But since we're not implementing tags yet, I'd leave that out, and question answers. 

For now, I'd only link to self, since that's all that we're implementing at the moment.

**Comment by anuditverma** [comment]
This has been fixed. Here is the commit https://github.com/anuditverma/OSDI-Implementation/commit/75189bfa44f6300fe69c627665e64838442bbf77
